version: '2'

services:
  api:
    image: 'dorsaydevelopment/idealist-api-staging:latest'
    ports:
      - '9000:80'
    links:
      - db
    environment:
      - API_URL=aurlihaventdecided
      - 'DB_CONN=mongodb://db/idealist'
      - NODE_ENV=staging
      - 'SECRET=super secret secret'
    restart: always

  web:
    image: 'dorsaydevelopment/idealist-web-staging:latest'
    ports:
      - '80:80'
    links:
      - api
    restart: always
    
  db:
    image: 'mongo:latest'
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-db:
    driver: local